// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuv5WF1PwwLOzjW967CpLjGxdfhZNJw6U',
    appId: '1:870447610086:web:64fe1d11c9b2a8161e2327',
    messagingSenderId: '870447610086',
    projectId: 'reddit-clone-flutter-769c0',
    authDomain: 'reddit-clone-flutter-769c0.firebaseapp.com',
    storageBucket: 'reddit-clone-flutter-769c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTZpz-ZNsokcGw9MkvAASG57jFBlBB7VQ',
    appId: '1:870447610086:android:5247f8df75b504251e2327',
    messagingSenderId: '870447610086',
    projectId: 'reddit-clone-flutter-769c0',
    storageBucket: 'reddit-clone-flutter-769c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRITUH5567CyhmY3YE7LNg7SXebRGU3cg',
    appId: '1:870447610086:ios:afa715ba8d4e525a1e2327',
    messagingSenderId: '870447610086',
    projectId: 'reddit-clone-flutter-769c0',
    storageBucket: 'reddit-clone-flutter-769c0.appspot.com',
    androidClientId: '870447610086-hin8ucp8pem8q7pdc46he4reo5eeoluc.apps.googleusercontent.com',
    iosClientId: '870447610086-bd98b8h9jav78q1ocum0qbvl5gc4f42l.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
